require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OnasController do

  # This should return the minimal set of attributes required to create a valid
  # Ona. As you add validations to Ona, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OnasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all onas as @onas" do
      ona = Ona.create! valid_attributes
      get :index, {}, valid_session
      assigns(:onas).should eq([ona])
    end
  end

  describe "GET show" do
    it "assigns the requested ona as @ona" do
      ona = Ona.create! valid_attributes
      get :show, {:id => ona.to_param}, valid_session
      assigns(:ona).should eq(ona)
    end
  end

  describe "GET new" do
    it "assigns a new ona as @ona" do
      get :new, {}, valid_session
      assigns(:ona).should be_a_new(Ona)
    end
  end

  describe "GET edit" do
    it "assigns the requested ona as @ona" do
      ona = Ona.create! valid_attributes
      get :edit, {:id => ona.to_param}, valid_session
      assigns(:ona).should eq(ona)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ona" do
        expect {
          post :create, {:ona => valid_attributes}, valid_session
        }.to change(Ona, :count).by(1)
      end

      it "assigns a newly created ona as @ona" do
        post :create, {:ona => valid_attributes}, valid_session
        assigns(:ona).should be_a(Ona)
        assigns(:ona).should be_persisted
      end

      it "redirects to the created ona" do
        post :create, {:ona => valid_attributes}, valid_session
        response.should redirect_to(Ona.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ona as @ona" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ona.any_instance.stub(:save).and_return(false)
        post :create, {:ona => {}}, valid_session
        assigns(:ona).should be_a_new(Ona)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ona.any_instance.stub(:save).and_return(false)
        post :create, {:ona => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ona" do
        ona = Ona.create! valid_attributes
        # Assuming there are no other onas in the database, this
        # specifies that the Ona created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ona.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ona.to_param, :ona => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ona as @ona" do
        ona = Ona.create! valid_attributes
        put :update, {:id => ona.to_param, :ona => valid_attributes}, valid_session
        assigns(:ona).should eq(ona)
      end

      it "redirects to the ona" do
        ona = Ona.create! valid_attributes
        put :update, {:id => ona.to_param, :ona => valid_attributes}, valid_session
        response.should redirect_to(ona)
      end
    end

    describe "with invalid params" do
      it "assigns the ona as @ona" do
        ona = Ona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ona.any_instance.stub(:save).and_return(false)
        put :update, {:id => ona.to_param, :ona => {}}, valid_session
        assigns(:ona).should eq(ona)
      end

      it "re-renders the 'edit' template" do
        ona = Ona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ona.any_instance.stub(:save).and_return(false)
        put :update, {:id => ona.to_param, :ona => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ona" do
      ona = Ona.create! valid_attributes
      expect {
        delete :destroy, {:id => ona.to_param}, valid_session
      }.to change(Ona, :count).by(-1)
    end

    it "redirects to the onas list" do
      ona = Ona.create! valid_attributes
      delete :destroy, {:id => ona.to_param}, valid_session
      response.should redirect_to(onas_url)
    end
  end

end
